spring:
  datasource:
    car:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/car
      username: root
      password: 1234
    recommend:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/recommend
      username: root
      password: 1234
