spring:
  datasource:
    car:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: ${{ secrets.CAR_DEFAULT_DATABASE_URL }}
      username: ${{ secrets.CAR_DEFAULT_DATABASE_USERNAME }}
      password: ${{ secrets.CAR_DEFAULT_DATABASE_PASSWORD }}
    recommend:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: ${{ secrets.RECOMMEND_DEFAULT_DATABASE_URL }}
      username: ${{ secrets.RECOMMEND_DEFAULT_DATABASE_USERNAME }}
      password: ${{ secrets.RECOMMEND_DEFAULT_DATABASE_PASSWORD }}
