spring:
  datasource:
    car:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: ${{car-default-database-url}}
      username: ${{car-default-database-username}}
      password: ${{car-default-database-password}}
    recommend:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: ${{recommend-default-database-url}}
      username: ${{recommend-default-database-username}}
      password: ${{recommend-default-database-password}}
