spring:
  datasource:
    recommend:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: ${RECOMMEND_DEFAULT_DATABASE_URL}
      username: ${RECOMMEND_DEFAULT_DATABASE_USERNAME}
      password: ${RECOMMEND_DEFAULT_DATABASE_PASSWORD}

module:
  car:
    protocol: ${MODULE_CAR_PROTOCOL}
    host: ${MODULE_CAR_HOST}
    port: ${MODULE_CAR_PORT}
