spring:
  datasource:
    recommend:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/recommend
      username: root
      password: 1234

module:
  car:
    protocol: http
    host: localhost
    port: 8080
