name: Backend CI

on:
  pull_request:
    branches: [ be/setting/10-CICD-구축 ]

jobs:
  backend-ci:
    runs-on: ubuntu-22.04
    steps:
      - name: 👋 Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: 🐬 Setup MySQL
        uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: "8.0"
          root-password: ${{ secrets.TEST_DB_PASSWORD }}

      - name: 🚗 Create Car Database
        run: mysql -h localhost -u root -p${{ secrets.TEST_DB_PASSWORD }} -e "${{ secrets.CAR_DB_DDL }}"

      - name: 👍 Create Recommend Database
        run: mysql -h localhost -u root -p${{ secrets.TEST_DB_PASSWORD }} -e "${{ secrets.RECOMMEND_DB_DDL }}"

      - name: 😪 Wait for DB
        run: sleep 10

      - name: ☕️ Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: 🔐 Grant execute permission for gradlew
        run: chmod +x ./gradlew
        working-directory: backend/boot-loader/
        shell: bash

      - name: 🛠 Build with Gradle with test profile
        run: sudo ./gradlew build -Pprofile=test
        working-directory: backend/boot-loader/
        shell: bash
