name: Backend CD

on:
  push:
    branches: [ backend ]

jobs:
  backend-ci:
    runs-on: ubuntu-22.04
    steps:
      - name: 👋 Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: 🐬 Setup MySQL
        uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: "8.0"
          root-password: ${{ secrets.TEST_DB_PASSWORD }}

      - name: 🚗 Create Car Database
        run: mysql -h localhost -u root -p${{ secrets.TEST_DB_PASSWORD }} -e "${{ secrets.CAR_DB_DDL }}"

      - name: 👍 Create Recommend Database
        run: mysql -h localhost -u root -p${{ secrets.TEST_DB_PASSWORD }} -e "${{ secrets.RECOMMEND_DB_DDL }}"

      - name: 😪 Wait for DB
        run: sleep 10

      - name: ☕️ Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: 🔐 Grant execute permission for gradlew
        run: chmod +x ./gradlew
        working-directory: backend/boot-loader/
        shell: bash

      - name: 🛠 Build with Gradle with test profile
        run: sudo ./gradlew build -Pprofile=test
        working-directory: backend/boot-loader/
        shell: bash

      - name: 🛠 Build with Gradle
        run: sudo ./gradlew build -x test -Pprofile=prod -Dskiptest
        working-directory: backend/boot-loader/
        shell: bash

      - name: ⚙️ Setup env
        env:
          SETUP_ENV: deploy/scripts/setup-env.sh
        run: |
          echo "export CAR_DEFAULT_DATABASE_URL="${{ secrets.CAR_DEFAULT_DATABASE_URL }} >> $SETUP_ENV && \
          echo "export CAR_DEFAULT_DATABASE_USERNAME="${{ secrets.CAR_DEFAULT_DATABASE_USERNAME }} >> $SETUP_ENV && \
          echo "export CAR_DEFAULT_DATABASE_PASSWORD="${{ secrets.CAR_DEFAULT_DATABASE_PASSWORD }} >> $SETUP_ENV && \
          echo "export RECOMMEND_DEFAULT_DATABASE_URL="${{ secrets.RECOMMEND_DEFAULT_DATABASE_URL }} >> $SETUP_ENV && \
          echo "export RECOMMEND_DEFAULT_DATABASE_USERNAME="${{ secrets.RECOMMEND_DEFAULT_DATABASE_USERNAME }} >> $SETUP_ENV && \
          echo "export RECOMMEND_DEFAULT_DATABASE_PASSWORD="${{ secrets.RECOMMEND_DEFAULT_DATABASE_PASSWORD }} >> $SETUP_ENV && \
          echo "export MODULE_CAR_PROTOCOL="${{ secrets.MODULE_CAR_PROTOCOL }} >> $SETUP_ENV && \
          echo "export MODULE_CAR_HOST="${{ secrets.MODULE_CAR_HOST }} >> $SETUP_ENV && \
          echo "export MODULE_CAR_PORT="${{ secrets.MODULE_CAR_PORT }} >> $SETUP_ENV

      - name: 📦 Make zip file
        run: zip -r ./$GITHUB_SHA.zip backend/boot-loader/build/libs/ appspec.yml deploy/scripts/
        shell: bash

      - name: 🔑 Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: 🗄️ Upload to S3
        env:
          REGION: ap-northreast-2
          S3_NAME: github-actions-codebuild-s3
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://$S3_NAME/$GITHUB_SHA.zip

  backend-cd:
    needs: [ backend-ci ]
    runs-on: ubuntu-latest
    steps:
      - name: 🔑 Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: 🫡 Code Deploy
        env:
          APPLICATION_NAME: codedeploy-app
          DEPLOY_GROUP: codedeploy-group
          S3_NAME: github-actions-codebuild-s3
        run: aws deploy create-deployment --application-name $APPLICATION_NAME
          --deployment-config-name CodeDeployDefault.OneAtATime
          --deployment-group-name $DEPLOY_GROUP
          --s3-location bucket=$S3_NAME,bundleType=zip,key=$GITHUB_SHA.zip
