name: Frontend CI/CD

on:
  push:
    branches: [ fe/setting/156-Frontend-CICD-구축 ]

jobs:
  frontend-ci:
    runs-on: ubuntu-latest
    steps:
      - name: 👋 Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: ☕️ Install npm
        run: sudo apt install nodejs
        shell: bash

      - name: ☕️ Install vite
        run: sudo npm install vite --save-dev
        shell: bash

      - name: 🛠 Build with npm
        run: sudo npm run build
        working-directory: front
        shell: bash

  frontend-cd:
    needs: [frontend-ci]
    runs-on: ubuntu-latest
    steps:
      - name: 🔑 Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: 🗄️ Upload to S3
        env:
          REGION: ap-northeast-2
          S3_NAME: my-car-store-front
        run: aws s3 cp --recursive --region ap-northeast-2 front/dist s3://$S3_NAME/dist
